src/carts/urls.py
from django.urls import path
from . import views

app_name = 'carts'
urlpatterns = [
    path('update_cart/', views.CartUpdate.as_view(), name='cart_update'),
    path('delete_good_in_cart/<int:pk>', views.DeleteGoodInCartView.as_view(), name='delete_good_in_cart'),
    path('', views.CartView.as_view(), name='cart_edit'),
]

src/catalog/urls.py
from django.urls import path
from . import views

app_name = "catalog"
urlpatterns = [
    path('', views.CatalogView.as_view(), name='catalog'),
    path('book/<int:pk>/', views.BookDetail.as_view(), name='book_detail'),
]

src/home_page/urls.py
from django.urls import path
from . import views 


app_name = "home_page"
urlpatterns = [
    path('', views.HomePage.as_view(), name='home_page'),
    path('login/', views.login_request, name='login'),
    path('register/', views.register_request, name='register'),
    path('logout/', views.logout_request, name= "logout"),
    
]

src/prod_card/urls.py
from django.urls import path
from . import views

app_name = "prod_card"
urlpatterns = [
    path('prod_card_detail/<int:pk>/', views.ShowProdCard.as_view(), name='prod_card_detail'),
    path('prod_card_create/', views.CreateProdCard.as_view(), name='prod_card_create'),
    path('prod_card_update/<int:pk>/', views.UpdateProdCard.as_view(), name='prod_card_update'),
    path('prod_card_delete/<int:pk>/', views.DeleteProdCard.as_view(), name='prod_card_delete'),
    path('prod_card_list/', views.ShowProdCardList.as_view(), name='prod_card_list')
]

src/proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from catalog.views import SearchResultView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('refs/', include ('reference_book.urls', namespace = 'reference_book')),
    path('', include ('home_page.urls', namespace = 'home_page')),
    path('prod_card/', include('prod_card.urls', namespace='prod_card')),
    path('catalog/', include('catalog.urls', namespace="catalog")),
    path('search/', SearchResultView.as_view(), name='search_results'),
    path('carts/', include('carts.urls', namespace="carts")),
    path('order/', include('order.urls', namespace="order")),
    path('admin_portal/', include('admin_portal.urls', namespace="admin_portal")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/catalog/models.py
from django.db import models
from django.contrib.auth.models import User
from prod_card.models import Books
from django.contrib.auth.models import AbstractBaseUser, UserManager, PermissionsMixin
from django.utils import timezone


class AppUser(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(
        unique=True,
        max_length=30,
    )
    name = models.CharField(max_length=40)
    surname = models.CharField(max_length=40)
    email = models.EmailField()
    index = models.IntegerField()
    phone = models.IntegerField(help_text="Enter the number.")
    country = models.CharField(max_length=30)
    city = models.CharField(max_length=40)
    address = models.CharField(max_length=50)
    reserve_address = models.CharField(blank=True, null=True, max_length=50)
    additional_info = models.CharField(blank=True, null=True, max_length=200)

    is_staff = models.BooleanField(default=False,)
    is_active = models.BooleanField(default=True,)
    is_superuser = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'username'

    class Meta:
        verbose_name = 'username'
        verbose_name_plural = 'usernames'
        abstract = False

class Comment(models.Model):
    book = models.ForeignKey(Books, on_delete=models.CASCADE,related_name='comments')
    username = models.ForeignKey('AppUser', on_delete=models.CASCADE, related_name='user_name')
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ['-created_date']

        def __str__(self):
            return self.text
    

src/prod_card/models.py
from django.db import models
from reference_book.models import Author
from reference_book.models import Series
from reference_book.models import Genre
from reference_book.models  import Publishing
from django.urls import reverse_lazy
from django.utils.datetime_safe import date
from django.core.exceptions import ValidationError

# Create your models here.

class Books(models.Model):
    
    name = models.CharField(
       max_length=60,
       verbose_name="Book name")

    logo = models.ImageField(
        verbose_name="Book logotip",
        upload_to='uploads/%Y/%m/%d/',
        blank=True,
        null=True)

    author = models.ManyToManyField(
        Author)

    price = models.DecimalField(
        max_digits=6, 
        decimal_places=2,
        verbose_name="Price",
        help_text="Currency in BYN")

    series = models.ForeignKey(
        Series,
        verbose_name="Series",
        on_delete=models.PROTECT)

    genre = models.ManyToManyField(
        Genre)

    publishing_year=models.CharField(
        max_length=10,
        verbose_name="Publishing year")

    pages = models.IntegerField(
        verbose_name="Pages")

    binding = models.CharField(
        max_length=30,
        verbose_name="Binding")

    format = models.CharField(
        max_length=8,
        verbose_name="Format")

    isbn = models.CharField(
        max_length=25,
        verbose_name="ISBN")

    weight = models.IntegerField(
        verbose_name="Weight")

    age_restriction = models.IntegerField( 
        verbose_name="Age restriction")

    publishing = models.ForeignKey(
        Publishing,
        verbose_name="Publishing",
        on_delete=models.PROTECT)

    available_books = models.IntegerField(
        verbose_name="Quantity  of books available")

    activity = models.CharField(
        max_length = 3,
        verbose_name="In stock")

    rating = models.DecimalField(
        max_digits=2, 
        decimal_places=1,
        verbose_name="Rating")

    date_of_addition = models.DateField(
        verbose_name="Date of addition")

    modification_date = models.DateTimeField(
        auto_now=True,
        verbose_name="Date the card was last modified")

    description = models.TextField(
        blank = True,
        null = True )
    

    def get_absolute_url(self):
        return reverse_lazy('prod_card:prod_card_detail', kwargs={'pk': self.pk})

    def clean(self):
        if str(self.date_of_addition) > str(date.today()):
            raise ValidationError({'date_of_addition': 'Must not be later than today!'})
            
    def __str__(self):
        return str(self.name)
        
    

src/catalog/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('text',)
        widgets = {
            'text': forms.Textarea(attrs={
                'class': 'form-control',
                'rows': 3
            })
      
        }
        
    

src/catalog/views.py
# Create your views here.
from django.shortcuts import render
from django.views import generic, View
from prod_card.models import Books
from .forms import CommentForm
from django.core.paginator import Paginator
from .models import Comment
from django.http import HttpResponse, HttpResponseRedirect
from django.db.models import Q
from django.shortcuts import get_object_or_404, render


class CatalogView(View):

    def get(self, request, *args, **kwargs):
        book = Books.objects.all()
        paginator = Paginator(book, 12)

        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)

        return render(
            request,
            'catalog/catalog.html',
            context={
                'page_obj': page_obj
            }
        )

class BookDetail(generic.DetailView):
    def get(self, request, *args, **kwargs):
        book = get_object_or_404(Books, pk=kwargs['pk'])
        last_posts = Books.objects.all().order_by('-id')[:3]
        comment_form = CommentForm()
        return render(request, 'catalog/book_detail.html', context={
            'book': book,
            'last_posts': last_posts,
            'comment_form': comment_form,
        })


    def post(self, request, *args, **kwargs):
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            text = request.POST['text']
            username = self.request.user
            book = get_object_or_404(Books, pk=kwargs['pk'])
            comment = Comment.objects.create(book=book, username=username,
                                             text=text)
            return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))
        return render(request, 'catalog/book_detail.html', context={
            'comment_form': comment_form
        })


class SearchResultView(View):
    def get(self, request, *args, **kwargs):
        query = self.request.GET.get('q')
        results = ''
        if query:
            results = Books.objects.filter(
                Q(author__name__icontains=query) | Q(name__icontains=query) | Q(author__surname__icontains=query) | Q(genre__genre_name__icontains=query) | Q(series__book_series__icontains=query)
            ).distinct()
        paginator = Paginator(results, 12)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        return render(request, 'catalog/search.html', context={
            'title': 'Search',
            'results': page_obj,
            'count': paginator.count,
        })

src/catalog/templates/catalog/book_deatil.html
{% extends "base.html" %}

{% block title %}
{{ object.name }}
{% endblock title %}

{% block content %}
<div class="shadow p-3 mb-5 bg-body rounded">
    <div class="text-center">
        <h2>{{ book.name }}</h2>
    </div>
</div>
<div class="shadow p-3 mb-5 bg-body rounded">
    <hr class="featurette-divider">
    <div class="row featurette">
        <div class="col-md-7 order-md-2">
        <h2 class="featurette-heading fw-normal lh-1">{{ book.name }}</h2><br>
        <h4 class="featurette-heading fw-normal lh-1" >Price:<span class="text-muted"><em> {{ book.price }} BYN</h4></em>
        <h4 class="featurette-heading fw-normal lh-1" >Author:<span class="text-muted"><em> {% for author in book.author.all %}{{ author }} {% endfor %}</h4></em>
        <h4 class="featurette-heading fw-normal lh-1" >Series:<span class="text-muted"><em> {{ book.series }}</h4></em>
        <h4 class="featurette-heading fw-normal lh-1" >Genre:<span class="text-muted"><em> {% for genre in book.genre.all %}{{ genre }} {% endfor %}</h4></em>
        <h4 class="featurette-heading fw-normal lh-1" >Year:<span class="text-muted"><em> {{ book.publishing_year }}</h4></em>
        <h4 class="featurette-heading fw-normal lh-1" >Pages:<span class="text-muted"><em> {{ book.pages }}</h4></em>
        <h4 class="featurette-heading fw-normal lh-1" >Binding:<span class="text-muted"><em> {{ book.binding }}</h4></em>
        <h4 class="featurette-heading fw-normal lh-1" >Format:<span class="text-muted"><em> {{ book.format }}</h4></em>
        <h4 class="featurette-heading fw-normal lh-1" >ISBN:<span class="text-muted"><em> {{ book.isbn }}</h4></em>
        <h4 class="featurette-heading fw-normal lh-1" >Weight:<span class="text-muted"><em> {{ book.weight }} gr</h4></em>
        <h4 class="featurette-heading fw-normal lh-1" >Age restriction:<span class="text-muted"><em> {{ book.age_restriction }}</h4></em>
        <h4 class="featurette-heading fw-normal lh-1" >Publisher:<span class="text-muted"><em> {{ book.publishing }}</h4></em>
        <h4 class="featurette-heading fw-normal lh-1" >Books available:<span class="text-muted"><em> {{ book.available_books }} pcs</h4></em>
        <h4 class="featurette-heading fw-normal lh-1" >Available for purchase:<span class="text-muted"><em> {{ book.activity }}</h4></em>
        <h4 class="featurette-heading fw-normal lh-1" >Rating:<span class="text-muted"><em> {{ book.rating }}</h4></em>
        
        <br>
        <h5 class="featurette-heading fw-normal lh-1" ><span class="text-muted"> {{ book.description }}</h5>
      </div>
      <div class="col-md-5 order-md-1">
        <img src="{{ book.image.url }}" width="500" height="500" border="1">
      </div>
    </div>
    <h6 class="featurette-heading fw-normal lh-1" >Changed:<span class="text-muted"><em> {{ book.modification_date }}</h6></em><br>

    <td><a href="{% url 'catalog:catalog' %}" class="btn btn-outline-secondary mb-3" onclick="history.go(-1); return false;">Cancel</a></td>     <td><a href="#" class="btn btn-outline-success mb-3">Add to cart</a></td>
    <hr>
    </div>
    <div class="card my-4">
      <h5 class="card-header">Leave the comment:</h5>
      {% if user.is_authenticated %}
      <div class="card-body">
          <form method="post">
              {% csrf_token %}
              <div class="form-group">
                  {{ comment_form.text }}
              </div>
              <br><button type="submit" class="btn btn-outline-primary">Save comment</button>
          </form>
      </div>
      {% else %}
      <h6 class="card-header"><a href="{% url 'home_page:login' %}">Login</a> or <a href="{% url 'home_page:register' %}">sign up</a> to leave the comment.</h6>
      {% endif %}
    </div>
    {% for comment in book.comments.all %}
    <div class="media mb-4">
      <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
      <div class="media-body">
        <div class="shadow p-3 mb-5 bg-body rounded">
          <h5 class="mt-0">{{comment.username}}</h5>
          {{comment.text}}
        </div>
      </div>
    </div>
    {% endfor %}


{% endblock content %}

src/catalog/templates/catalog/book_detail.html
{% extends "base.html" %}

{% block title %}
{{ object.name }}
{% endblock title %}

{% block content %}
<div class="shadow p-3 mb-5 bg-body rounded">
    <div class="text-center">
        <h2>{{ book.name }}</h2>
    </div>
</div>
<div class="shadow p-3 mb-5 bg-body rounded">
    <hr class="featurette-divider">
    <div class="row featurette">
        <div class="col-md-7 order-md-2">
        <h2 class="featurette-heading fw-normal lh-1">{{ book.name }}</h2><br>
        <h4 class="featurette-heading fw-normal lh-1" >Price:<span class="text-muted"><em> {{ book.price }} BYN</h4></em>
        <h4 class="featurette-heading fw-normal lh-1" >Author:<span class="text-muted"><em> {% for author in book.author.all %}{{ author }} {% endfor %}</h4></em>
        <h4 class="featurette-heading fw-normal lh-1" >Series:<span class="text-muted"><em> {{ book.series }}</h4></em>
        <h4 class="featurette-heading fw-normal lh-1" >Genre:<span class="text-muted"><em> {% for genre in book.genre.all %}{{ genre }} {% endfor %}</h4></em>
        <h4 class="featurette-heading fw-normal lh-1" >Year:<span class="text-muted"><em> {{ book.publishing_year }}</h4></em>
        <h4 class="featurette-heading fw-normal lh-1" >Pages:<span class="text-muted"><em> {{ book.pages }}</h4></em>
        <h4 class="featurette-heading fw-normal lh-1" >Binding:<span class="text-muted"><em> {{ book.binding }}</h4></em>
        <h4 class="featurette-heading fw-normal lh-1" >Format:<span class="text-muted"><em> {{ book.format }}</h4></em>
        <h4 class="featurette-heading fw-normal lh-1" >ISBN:<span class="text-muted"><em> {{ book.isbn }}</h4></em>
        <h4 class="featurette-heading fw-normal lh-1" >Weight:<span class="text-muted"><em> {{ book.weight }} gr</h4></em>
        <h4 class="featurette-heading fw-normal lh-1" >Age restriction:<span class="text-muted"><em> {{ book.age_restriction }}</h4></em>
        <h4 class="featurette-heading fw-normal lh-1" >Publisher:<span class="text-muted"><em> {{ book.publishing }}</h4></em>
        <h4 class="featurette-heading fw-normal lh-1" >Books available:<span class="text-muted"><em> {{ book.available_books }} pcs</h4></em>
        <h4 class="featurette-heading fw-normal lh-1" >Available for purchase:<span class="text-muted"><em> {{ book.activity }}</h4></em>
        <h4 class="featurette-heading fw-normal lh-1" >Rating:<span class="text-muted"><em> {{ book.rating }}</h4></em>

        <br>
        <h5 class="featurette-heading fw-normal lh-1" ><span class="text-muted"> {{ book.description }}</h5>
      </div>
      <div class="col-md-5 order-md-1">
        <img src="{{ book.logo.url }}" width="350" height="500" >
      </div>
    </div>
    {% if perms.prod_card.delete_books%}
    <h6 class="featurette-heading fw-normal lh-1" >Changed:<span class="text-muted"><em> {{ book.modification_date }}</h6></em><br>
     {% endif %}
      <form action="{%url 'carts:cart_edit' %}" method="get">
        {% csrf_token %}
      <td><a href="{% url 'catalog:catalog' %}" class="btn btn-outline-secondary mb-3">Cancel</a></td> {% comment %}onclick="history.go(-1); return false; {% endcomment %}
      <td><button type="submit" class="btn btn-outline-success mb-3">Add to cart</button></td>
      <input type="hidden" name="book_pk" value="{{ book.pk }}">
      </form>
    <hr>
    </div>
    <div class="card my-4">
      <h5 class="card-header">Commentary:</h5>
      {% if user.is_authenticated %}
      <div class="card-body">
          <form method="post">
              {% csrf_token %}
              <div class="form-group">
                  {{ comment_form.text }}
              </div>
              <br><button type="submit" class="btn btn-outline-primary">Save comment</button>
          </form>
      </div>
      {% else %}
      <h6 class="card-header"><a href="{% url 'home_page:login' %}?next={{ request.path }}">Login</a> or <a href="{% url 'home_page:register' %}?next={{ request.path }}">sign up</a> to leave the comment.</h6>
      {% endif %}
    </div>
    {% for comment in book.comments.all %}
    <div class="media mb-4">
      <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
      <div class="media-body">
        <div class="shadow p-3 mb-5 bg-body rounded">
          <h5 class="mt-0">{{comment.username}}</h5>
          {{comment.text}}
        </div>
      </div>
    </div>
    {% endfor %}


{% endblock content %}

src/catalog/templates/catalog/catalog.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'bs/css/bootstrap.min.css' %}" rel="stylesheet">
    <script src="{% static 'bs/js/bootstrap.min.js' %}"></script>
    <link href="{% static 'bs/css/custom.css' %}" rel="stylesheet">


</head>
<body>

<header>
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">BSHOP</a><br>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/catalog">Catalog</a>
          </li>

          <li class="nav-item">
            <a class="nav-link active" href="/refs/rb/">Authors</a>
          </li>

          <li class="nav-item">
            <a class="nav-link active" href="/refs/rb-genre/">Genres</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="/refs/rb-Publishing/">Publishing</a>
          </li>

         {% if perms.prod_card.delete_books%}
          <li class="nav-item">
            <a class="nav-link active" href="/admin/">Administration portal</a>
          </li>
          {% endif %}
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'carts:cart_edit' %}">Order</a>
          </li>
        </ul>
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link"  href="https://www.nbrb.by/statistics/rates/ratesdaily.asp">2.5 USD/BYN</a>
            </li>
          </ul>

          <form action="{% url 'search_results' %}" method="get" class="d-flex" role="search">
            <input name="q" type="text" class="form-control me-2" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-info me-4" type="submit">
              <i class="bi bi-search">
              </i>
            </button>
          </form>

        <li style="list-style-type: none">
        {% if user.is_authenticated %}
  <span class="navbar-text mr-2">{{ user }}</span>
  <a href="/logout" class="btn btn-outline-light"><i class="bi bi-box-arrow-right">

  </i></a>
{% else %}
  <a href="{% url 'home_page:login' %}" class="btn btn-outline-light">Log in</i></a>
  <a href="{% url 'home_page:register' %}" class="btn btn-outline-light">Sign up</a>
{% endif %}
        </li>
      </div>
    </div>
  </nav>
</header>

<main>

<section class="py-5 text-center container">
  <div class="row py-lg-5">
    <div class="col-lg-6 col-md-8 mx-auto">
      <h1 class="fw-light">Happy choice!</h1>

    </div>
  </div>
</section>

<div class="album py-5 bg-light">
  <div class="container size-fixed">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
      {% for obj in page_obj %}
      <div class="col">
        <div class="card shadow-sm">
           <img src="{{ obj.logo.url }}"  width="100%" height="500">
          <div class="card-body">
            <p class="card-text">{{ obj.description }}</p>
            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
                <a href="{% url 'catalog:book_detail' pk=obj.pk %}"  type="submit" class="btn btn-sm btn-outline-secondary">View</a>
                {% if perms.prod_card.delete_books%}
                <a href="{% url 'prod_card:prod_card_update' pk=obj.pk %}" type="button" class="btn btn-sm btn-outline-secondary">Edit</a>
                {% endif %}
              </div>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
</main>


<footer class="py-3 my-4">
  <div class="shadow p-3 mb-5 bg-body rounded">
  <div class="container">
    <p class="text-center text-muted">&copy; 2022 BSHOP, Inc</p>
  </div>
  </div>
</footer>
</main>
</body>
</html>

src/catalog/templates/catalog/search.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Search{% endblock %}



{% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-12">

            <p class="lead">Results found: {{ count }}</p>
            {% for result in results %}
                <a href="{% url 'catalog:book_detail' pk=result.pk %}"><h2>{{ result.name }}</h2></a>
                Author: {% for author in result.author.all %}{{ author }} {% endfor %}<br>
                Genre: {% for genre in result.genre.all %}{{ genre }} {% endfor %}<br>
                Series: {{ result.series }}<br>
                Description: {{ result.description|safe }}
                <hr>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

{% block pagination %}
    <nav aria-label="Paginate me">
      <ul class="pagination justify-content-center">
        {% if results.has_previous %}
          <a class="page-link" href="?page={{ results.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}" tabindex="-1">Previous</a>
        {% else %}
        <li class="page-item disabled">
          <a class="page-link disabled" href="#" tabindex="-1">Previous</a>
        </li>
        {% endif %}
        {% for i in results.paginator.page_range %}
        {% if i == results.number %}
          <li class="page-item active"><a class="page-link" href="?page={{ i }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">{{ i }}</a></li>
        {% else %}
          <li class="page-item"><a class="page-link" href="?page={{ i }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">{{ i }}</a></li>
        {% endif %}
        {% endfor %}
        {% if results.has_next %}
          <a class="page-link" href="?page={{ results.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">Next</a>
        {% else %}
          <li class="page-item disabled">
            <a class="page-link" href="#">Next</a>
          </li>
        {% endif %}
      </ul>
    </nav>
    <br>
{% endblock %}