src/prod_card/urls.py
from django.urls import path
from . import views

app_name = "prod_card"
urlpatterns = [
    path('prod_card_detail/<int:pk>/', views.ShowProdCard.as_view(), name='prod_card_detail'),
    path('prod_card_create/', views.CreateProdCard.as_view(), name='prod_card_create'),
    path('prod_card_update/<int:pk>/', views.UpdateProdCard.as_view(), name='prod_card_update'),
    path('prod_card_delete/<int:pk>/', views.DeleteProdCard.as_view(), name='prod_card_delete'),
    path('prod_card_list/', views.ShowProdCardList.as_view(), name='prod_card_list')
]

src/proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from catalog.views import SearchResultView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('refs/', include ('reference_book.urls', namespace = 'reference_book')),
    path('', include ('home_page.urls', namespace = 'home_page')),
    path('prod_card/', include('prod_card.urls', namespace='prod_card')),
    path('catalog/', include('catalog.urls', namespace="catalog")),
    path('search/', SearchResultView.as_view(), name='search_results'),
    path('carts/', include('carts.urls', namespace="carts")),
    path('order/', include('order.urls', namespace="order")),
    path('admin_portal/', include('admin_portal.urls', namespace="admin_portal")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/reference_book/urls.py
from django.urls import path
from . import views 
app_name = 'reference_book'
urlpatterns = [
    path('rb/<int:pk>/', views.ShowAuthor.as_view(), name = 'author-detail'),
    path('rb-create/', views.CreateAuthor.as_view(), name = 'author-create'),
    path('rb-update/<int:pk>/', views.UpdateAuthor.as_view(), name = 'author-update'),
    path('rb-delete/<int:pk>/', views.DeleteAuthor.as_view(), name = 'author-delete'),
    path('rb/', views.ShowAuthors.as_view(), name = 'author-list'),

    path('rb-seies/<int:pk>/', views.ShowSeries.as_view(), name = 'series-detail'),
    path('rb-create-seies/', views.CreateSeries.as_view(), name = 'series-create'),
    path('rb-update-seies/<int:pk>/', views.UpdateSeries.as_view(), name = 'series-update'),
    path('rb-delete-seies/<int:pk>/', views.DeleteSeries.as_view(), name = 'series-delete'),
    path('rb-seies/', views.ShowSerie.as_view(), name = 'series-list'),
   
    path('rb-genre/<int:pk>/', views.ShowGenre.as_view(), name = 'genre-detail'),
    path('rb-create-genre/', views.CreateGenre.as_view(), name = 'genre-create'),
    path('rb-update-genre/<int:pk>/', views.UpdateGenre.as_view(), name = 'genre-update'),
    path('rb-delete-genre/<int:pk>/', views.DeleteGenre.as_view(), name = 'genre-delete' ),
    path('rb-genre/', views.ShowGenres.as_view(),name = 'genre-list'),

    path('rb-Publishing/<int:pk>/', views.ShowPublishing.as_view(), name = 'publishing-detail'),
    path('rb-create-Publishing/', views.CreatePublishing.as_view(), name = 'publishing-create'),
    path('rb-update-Publishing/<int:pk>/', views.UpdatePublishing.as_view(), name = 'publishing-update'),
    path('rb-delete-Publishing/<int:pk>/', views.DeletePublishing.as_view(), name = 'publishing-delete'),
    path('rb-Publishing/', views.ShowPublishings.as_view(), name = 'publishing-list'),
    
    ]

src/prod_card/models.py
from django.db import models
from reference_book.models import Author
from reference_book.models import Series
from reference_book.models import Genre
from reference_book.models  import Publishing
from django.urls import reverse_lazy
from django.utils.datetime_safe import date
from django.core.exceptions import ValidationError

# Create your models here.

class Books(models.Model):
    
    name = models.CharField(
       max_length=60,
       verbose_name="Book name")

    logo = models.ImageField(
        verbose_name="Book logotip",
        upload_to='uploads/%Y/%m/%d/',
        blank=True,
        null=True)

    author = models.ManyToManyField(
        Author)

    price = models.DecimalField(
        max_digits=6, 
        decimal_places=2,
        verbose_name="Price",
        help_text="Currency in BYN")

    series = models.ForeignKey(
        Series,
        verbose_name="Series",
        on_delete=models.PROTECT)

    genre = models.ManyToManyField(
        Genre)

    publishing_year=models.CharField(
        max_length=10,
        verbose_name="Publishing year")

    pages = models.IntegerField(
        verbose_name="Pages")

    binding = models.CharField(
        max_length=30,
        verbose_name="Binding")

    format = models.CharField(
        max_length=8,
        verbose_name="Format")

    isbn = models.CharField(
        max_length=25,
        verbose_name="ISBN")

    weight = models.IntegerField(
        verbose_name="Weight")

    age_restriction = models.IntegerField( 
        verbose_name="Age restriction")

    publishing = models.ForeignKey(
        Publishing,
        verbose_name="Publishing",
        on_delete=models.PROTECT)

    available_books = models.IntegerField(
        verbose_name="Quantity  of books available")

    activity = models.CharField(
        max_length = 3,
        verbose_name="In stock")

    rating = models.DecimalField(
        max_digits=2, 
        decimal_places=1,
        verbose_name="Rating")

    date_of_addition = models.DateField(
        verbose_name="Date of addition")

    modification_date = models.DateTimeField(
        auto_now=True,
        verbose_name="Date the card was last modified")

    description = models.TextField(
        blank = True,
        null = True )
    

    def get_absolute_url(self):
        return reverse_lazy('prod_card:prod_card_detail', kwargs={'pk': self.pk})

    def clean(self):
        if str(self.date_of_addition) > str(date.today()):
            raise ValidationError({'date_of_addition': 'Must not be later than today!'})
            
    def __str__(self):
        return str(self.name)
        
    

src/reference_book/models.py
from tabnanny import verbose

from django.db import models
from django.urls import reverse_lazy

# Create your models here.
class Author(models.Model):
    name = models.CharField(max_length = 50,verbose_name ='Author')
    surname = models.CharField(max_length=30,verbose_name="Author's surname",)    
    description = models.TextField(blank=True,null=True)
    def __str__(self):
        return self.name + ' ' + self.surname
    
    def get_absolute_url(self):
        return reverse_lazy('reference_book:author-detail', kwargs = {'pk': self.pk})
        #return f'/rb/{self.pk}/'
                
            
class Series(models.Model):
    book_series = models.CharField(max_length = 50)
    description = models.TextField(blank = True,null = True)
    def __str__(self):
        return self.book_series  
    def get_absolute_url(self):
        return reverse_lazy('reference_book:series-detail', kwargs = {'pk': self.pk})
           

class Genre(models.Model):        
    genre_name = models.CharField(max_length = 50)
    description = models.TextField(blank=True,null=True)
    def __str__(self):
        return self.genre_name

    def get_absolute_url(self):
        return reverse_lazy('reference_book:genre-detail', kwargs = {'pk': self.pk})
          

class Publishing(models.Model):
    publishing_name = models.CharField(max_length = 50)
    description = models.TextField(blank=True,null=True)
    def __str__(self):
        return self.publishing_name 
    def get_absolute_url(self):
        return reverse_lazy('reference_book:publishing-detail', kwargs = {'pk': self.pk})
                  
   
    

src/reference_book/forms.py
from django import forms
from django.core.exceptions import ValidationError
from . import models 



def name_validator(value:str):
    if value.startswith(' '):
        raise ValidationError('Must not srart with " "')
    return value

class AuthorForm(forms.ModelForm):
    class Meta:
        model=models.Author
        fields=['name', 'surname', 'description' ]    
      

#class SeriesForm(forms.Form):
    #name = forms.CharField(max_length=50)
    #number_series = forms.IntegerField()

class SeriesForm(forms.ModelForm):
    class Meta:
        model = models.Series
        fields = ['book_series','description']

 
class GenreForm(forms.ModelForm):
    class Meta:
        model = models.Genre
        fields = ['genre_name','description']

class PublishingForm(forms.ModelForm):
    class Meta:
        model = models.Publishing
        fields = ['publishing_name','description']

src/reference_book/views.py
import datetime
from django.views import generic
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from . import models,forms
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin

# Create your views here.
class ShowAuthors (LoginRequiredMixin, PermissionRequiredMixin,generic.ListView):
    model = models.Author
    template_name = 'reference_book/list_author.html'
    login_url = 'home_page:login'
    permission_required = 'reference_book.view_author'

class ShowAuthor (LoginRequiredMixin, PermissionRequiredMixin,generic.DetailView):
    model = models.Author
    template_name = 'reference_book/detail_author.html'
    login_url = 'home_page:login'
    permission_required = 'reference_book.view_author'

class CreateAuthor (LoginRequiredMixin, PermissionRequiredMixin,generic.CreateView):
    model = models.Author
    form_class = forms.AuthorForm
    template_name = 'reference_book/edit_author.html'
    login_url = 'home_page:login'
    permission_required = 'reference_book.add_author'
    def get_context_data(self, *args, **kwargs):
            context = super().get_context_data(*args,**kwargs)
            context['crup_name'] = 'Create'
            return context

class UpdateAuthor (LoginRequiredMixin, PermissionRequiredMixin,generic.UpdateView):
    model=models.Author
    form_class = forms.AuthorForm
    template_name = 'reference_book/edit_author.html'
    login_url = 'home_page:login'
    permission_required = 'reference_book.change_author'
    def get_context_data(self, *args, **kwargs):
            context = super().get_context_data(*args,**kwargs)
            context['crup_name'] = 'Update'
            return context

class DeleteAuthor (LoginRequiredMixin, PermissionRequiredMixin,generic.DeleteView):
    model=models.Author
    template_name = 'reference_book/delete_author.html'
    login_url = 'home_page:login'
    permission_required = 'reference_book.delete_author'
    def get_success_url(self):
        return reverse_lazy('reference_book:authors_list')

class ShowSerie(LoginRequiredMixin, PermissionRequiredMixin,generic.ListView):
    model = models.Series
    template_name = 'reference_book/list_series.html'
    login_url = 'home_page:login'
    permission_required = 'reference_book.view_series'

class ShowSeries (LoginRequiredMixin, PermissionRequiredMixin,generic.DetailView):
    model = models.Series
    template_name = 'reference_book/detail_series.html'
    login_url = 'home_page:login'
    permission_required = 'reference_book.view_series'

class CreateSeries (LoginRequiredMixin, PermissionRequiredMixin,generic.CreateView):
    model = models.Series
    form_class = forms.SeriesForm
    template_name = 'reference_book/edit_series.html'
    login_url = 'home_page:login'
    permission_required = 'reference_book.add_series'
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args,**kwargs)
        context['crup_name'] = 'Create'
        return context

class UpdateSeries (LoginRequiredMixin, PermissionRequiredMixin,generic.UpdateView):
    model=models.Series
    form_class = forms.SeriesForm
    template_name = 'reference_book/edit_series.html'
    login_url = 'home_page:login'
    permission_required = 'reference_book.change_series'
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args,**kwargs)
        context['crup_name'] = 'Update'
        return context

class DeleteSeries(LoginRequiredMixin, PermissionRequiredMixin,generic.DeleteView):
    model=models.Series
    form_class = forms.SeriesForm
    template_name = 'reference_book/delete_series.html'
    login_url = 'home_page:login'
    permission_required = 'reference_book.delete_series'
    def get_success_url(self):
        return reverse_lazy('reference_book:series_list')


class ShowGenres(LoginRequiredMixin, PermissionRequiredMixin,generic.ListView):
    model = models.Genre
    template_name = 'reference_book/list_genre.html'
    login_url = 'home_page:login'
    permission_required = 'reference_book.view_genre'

class ShowGenre (LoginRequiredMixin, PermissionRequiredMixin,generic.DetailView):
    model = models.Genre
    template_name = 'reference_book/detail_genre.html'
    login_url = 'home_page:login'
    permission_required = 'reference_book.view_genre'

class CreateGenre (LoginRequiredMixin, PermissionRequiredMixin,generic.CreateView):
    model = models.Genre
    form_class = forms.GenreForm
    template_name = 'reference_book/edit_genre.html'
    login_url = 'home_page:login'
    permission_required = 'reference_book.add_genre'
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args,**kwargs)
        context['crup_name'] = 'Create'
        return context

class UpdateGenre (LoginRequiredMixin, PermissionRequiredMixin,generic.UpdateView):
    model=models.Genre
    form_class = forms.GenreForm
    template_name = 'reference_book/edit_genre.html'
    login_url = 'home_page:login'
    permission_required = 'reference_book.change_genre'
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args,**kwargs)
        context['crup_name'] = 'Update'
        return context

class DeleteGenre(LoginRequiredMixin, PermissionRequiredMixin,generic.DeleteView):
    model=models.Genre
    form_class = forms.GenreForm
    template_name = 'reference_book/delete_genre.html'
    login_url = 'home_page:login'
    permission_required = 'reference_book.delete_genre'
    def get_success_url(self):
        return reverse_lazy('reference_book:genres_list')

class ShowPublishings(LoginRequiredMixin, PermissionRequiredMixin,generic.ListView):
    model = models.Publishing
    template_name = 'reference_book/list_publishing.html'
    login_url = 'home_page:login'
    permission_required = 'reference_book.view_publishing'

class ShowPublishing (LoginRequiredMixin, PermissionRequiredMixin,generic.DetailView):
    model = models.Publishing
    template_name = 'reference_book/detail_publishing.html'
    login_url = 'home_page:login'
    permission_required = 'reference_book.view_publishing'

class CreatePublishing (LoginRequiredMixin, PermissionRequiredMixin,generic.CreateView):
    model = models.Publishing
    form_class = forms.PublishingForm
    template_name = 'reference_book/edit_publishing.html'
    login_url = 'home_page:login'
    permission_required = 'reference_book.add_publishing'
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args,**kwargs)
        context['crup_name'] = 'Create'
        return context

class UpdatePublishing (LoginRequiredMixin, PermissionRequiredMixin,generic.UpdateView):
    model=models.Publishing
    form_class = forms.PublishingForm
    template_name = 'reference_book/edit_publishing.html'
    login_url = 'home_page:login'
    permission_required = 'reference_book.change_publishing'
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args,**kwargs)
        context['crup_name'] = 'Update'
        return context

class DeletePublishing(LoginRequiredMixin, PermissionRequiredMixin,generic.DeleteView):
    model=models.Publishing
    form_class = forms.PublishingForm
    template_name = 'reference_book/delete_publishing.html'
    login_url = 'home_page:login'
    permission_required = 'reference_book.delete_publishing'

    def get_success_url(self):
        return reverse_lazy('reference_book:publishing_list')

src/reference_book/templates/reference_book/delete_author.html
{% extends "base.html" %}

{% block title %}
Delete author
{% endblock title %}

{% block content %}
<div class="shadow p-3 mb-5 bg-body rounded">
<div class="text-center">
    <h1>Do you want to remove the author?</h1><br>
</div>
</div>
<p>Author <b>"{{ object.name }} {{ object.surname}}"</b> will be deleted.<br>
    Please click delete button.</p><br>
    Description: {{ object.description|default:"No description" }}<br>
    <br>
    <form action="" method="post">
        {% csrf_token %}
        <a href="{% url 'reference_book:author-list' %}" class="btn btn-secondary">Cancel</i></a>
        <input type="submit" value="Delete" class="btn btn-danger">
    </form>
{% endblock content %}

src/reference_book/templates/reference_book/delete_genre.html
{% extends "base.html" %}

{% block title %}
Delete genre
{% endblock title %}

{% block content %}
<div class="shadow p-3 mb-5 bg-body rounded">
    <div class="text-center">
        <h1>Do you want to remove the genre??</h1><br>
    </div>
    </div>
    <p>Genre <b>"{{ object.genre_name }}"</b> will be deleted.<br>
        Please click delete button.</p><br>
        Description: {{ object.description|default:"No description" }}<br>
        <br>
    <form action="" method="post">
        {% csrf_token %}
        <a href="{% url 'reference_book:genre-list' %}" class="btn btn-secondary">Cancel</i></a>
        <input type="submit" value="Delete" class="btn btn-danger">
    </form>
{% endblock content %}

src/reference_book/templates/reference_book/detail_author.html
{% extends "base.html" %}

{% block title %}
Author's
{% endblock title %}

{% block content %}
<div class="shadow p-3 mb-5 bg-body rounded">
    <div class="text-center">
        <h1><span style="color: blue;">Author </span></h1>
    </div>
    </div>
    Author's data: <b>"{{ object.name }} {{object.surname}}"</b><br>
    Description: {{ object.description|default:"No description" }}<br>
    <br>
    {% if perms.prod_card.view_books%}
    <td><a href="{% url 'reference_book:author-create' %}" class="btn btn-outline-success mb-3">Create a new author</a></td>
    {% endif %}
    <br>
    <td><a href="{% url 'reference_book:author-list' %}" class="btn btn-outline-success mb-3">Show the list of authors</a></td>
{% endblock content %}

src/reference_book/templates/reference_book/detail_genre.html
{% extends "base.html" %}

{% block title %}
Genre
{% endblock title %}

{% block content %}
<div class="shadow p-3 mb-5 bg-body rounded">
    <div class="text-center">
        <h1><span style="color: blue;">Genre</span></h1>
    </div>
    </div>
    Genre name: <b>"{{ object.genre_name }}"</b><br>
    Description: {{ object.description|default:"No description" }}<br>
    <br>
    {% if perms.prod_card.view_books%}
    <td><a href="{% url 'reference_book:genre-create' %}" class="btn btn-outline-success mb-3">Create a new genre</a></td>
    {% endif %}
    <br>
    <td><a href="{% url 'reference_book:genre-list' %}" class="btn btn-outline-success mb-3">Show the list of genres</a></td>
{% endblock content %}

src/reference_book/templates/reference_book/detail_publishing.html
{% extends "base.html" %}

{% block title %}
Publishing
{% endblock title %}

{% block content %}
<div class="shadow p-3 mb-5 bg-body rounded">
    <div class="text-center">
        <h1><span style="color: blue;">Publishing</span></h1>
    </div>
    </div>
    Publishing : <b>"{{ object.publishing_name }}"</b><br>
    Description: {{ object.description|default:"No description" }}<br>
    <br>
     {% if perms.prod_card.view_books%}
    <td><a href="{% url 'reference_book:publishing-create' %}" class="btn btn-outline-success mb-3">Create a new publishing </a></td>
      {% endif %}
    <br>
    <td><a href="{% url 'reference_book:publishing-list' %}" class="btn btn-outline-success mb-3">Show the list of publishing </a></td>
{% endblock content %}

src/reference_book/templates/reference_book/detail_series.html
{% extends "base.html" %}

{% block title %}
Series
{% endblock title %}

{% block content %}
<div class="shadow p-3 mb-5 bg-body rounded">
    <div class="text-center">
        <h1><span style="color: blue;">Book's series</span></h1>
    </div>
    </div>
    Series name: <b>"{{ object.book_series }}"</b><br>
    Description: {{ object.description|default:"No description" }}<br>
    <br>
    <td><a href="{% url 'reference_book:series-create' %}" class="btn btn-outline-success mb-3">Create a new series</a></td>
    <br>
    <td><a href="{% url 'reference_book:series-list' %}" class="btn btn-outline-success mb-3">Show the list of series</a></td>
{% endblock content %}

src/reference_book/templates/reference_book/list_author.html
{% extends "base.html" %}

{% block title %}List of authors{% endblock title %}

{% block content %}
<div class="shadow p-3 mb-5 bg-body rounded">
    <div class="text-center">
        <h1>List of authors</h1>
    </div>
    </div>
        {% if perms.prod_card.delete_books%}
        <td><a href="{% url 'reference_book:author-create' %}" class="btn btn-outline-success mb-3">Create a new author</a></td>
         {% endif %}
        <div class="shadow p-3 mb-5 bg-body rounded">
        <div class="table-responsive">
        <div class="text-center">
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                  <th scope="col">Authors name</th>
                  {% if perms.prod_card.delete_books%}
                  <th scope="col">Options</th>
                  {% endif %}
                </tr>
              </thead>
            <tbody>
        {% for obj in object_list %}
        <tr>
            <td><a href="{% url 'prod_card:prod_card_detail' pk=obj.pk %}"> {{ obj.name }} {{ obj.surname }}</a> </td>
             {% if perms.prod_card.delete_books%}
            <td><a href="{% url 'reference_book:author-update' pk=obj.pk %}" class="btn btn-outline-primary"><i class="bi bi-pencil-square"></i></a>
                <a href="{% url 'reference_book:author-delete' pk=obj.pk %}" class="btn btn-outline-danger" data-bs-toggle="modal" data-bs-target="#id{{obj.pk}}"><i class="bi bi-x-lg"></i></a></td>
                {% endif %}
        </tr>
                <!-- Modal -->
<div class="modal fade" id="id{{obj.pk}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">Do you want to remove the author?</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            Author <b>"{{ obj.name }} {{ obj.surname }}"</b> will be deleted.
            Please click delete button.<br>
            <br>
            <form action="{% url 'reference_book:author-delete' pk=obj.pk %}" method="post">
                {% csrf_token %}
                <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <input type="submit" value="Delete" class="btn btn-danger">
            </form>
        </div>
        </div>
      </div>
    </div>
  </div>
            </tbody>
        </div>
        {% endfor %}
        </table>
{% endblock content %}

src/reference_book/templates/reference_book/list_genre.html
{% extends "base.html" %}

{% block title %}List of genres{% endblock title %}

{% block content %}
<div class="shadow p-3 mb-5 bg-body rounded">
    <div class="text-center">
        <h1>List of genres</h1>
    </div>
    </div>
    {% if perms.prod_card.delete_books%}
        <td><a href="{% url 'reference_book:genre-create' %}" class="btn btn-outline-success mb-3">Create a new genre</a></td>
        {% endif %}
        <div class="shadow p-3 mb-5 bg-body rounded">
        <div class="table-responsive">
        <div class="text-center">
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                  <th scope="col">Genre name</th>
                  {% if perms.prod_card.delete_books%}
                  <th scope="col">Options</th>
                  {% endif %}
                </tr>
              </thead>
            <tbody>
        {% for obj in object_list %}
        <tr>
            <td><a href="{% url 'prod_card:prod_card_detail'  pk=obj.pk %}"> {{ obj.genre_name }}</a></td>
            {% if perms.prod_card.delete_books%}
            <td><a href="{% url 'reference_book:genre-update' pk=obj.pk %}" class="btn btn-outline-primary"><i class="bi bi-pencil-square"></i></a>
                <a href="{% url 'reference_book:genre-delete' pk=obj.pk %}" class="btn btn-outline-danger" data-bs-toggle="modal" data-bs-target="#id{{obj.pk}}"><i class="bi bi-x-lg"></i></a></td>
                {% endif %}
        </tr>
                <!-- Modal -->
<div class="modal fade" id="id{{obj.pk}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">Do you want to remove the author?</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            Genre <b>"{{ obj.genre_name }}"</b> will be deleted.
            Please click delete button.<br>
            <br>
            <form action="{% url 'reference_book:genre-delete' pk=obj.pk %}" method="post">
                {% csrf_token %}
                <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <input type="submit" value="Delete" class="btn btn-danger">
            </form>
        </div>
        </div>
      </div>
    </div>
  </div>
            </tbody>
        </div>
        {% endfor %}
        </table>
{% endblock content %}

src/reference_book/templates/reference_book/list_series.html
{% extends "base.html" %}

{% block title %}List of series{% endblock title %}


{% block content %}
<div class="shadow p-3 mb-5 bg-body rounded">
    <div class="text-center">
        <h1>List of series</h1>
    </div>
    </div>
        <td><a href="{% url 'reference_book:series-create' %}" class="btn btn-outline-success mb-3">Create a new series</a></td>
        <div class="shadow p-3 mb-5 bg-body rounded">
        <div class="table-responsive">
        <div class="text-center">
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                  <th scope="col">Series</th>
                  <th scope="col">Options</th>
                </tr>
              </thead>
            <tbody>
        {% for obj in object_list %}
        <tr>
            <td><a href="{% url 'prod_card:prod_card_detail' pk=obj.pk %}">{{ obj.book_series }}</a></td>
            <td><a href="{% url 'reference_book:series-update' pk=obj.pk %}" class="btn btn-outline-primary"><i class="bi bi-pencil-square"></i></a>
                <a href="{% url 'reference_book:series-delete' pk=obj.pk %}" class="btn btn-outline-danger" data-bs-toggle="modal" data-bs-target="#id{{obj.pk}}"><i class="bi bi-x-lg"></i></a></td>
        </tr>
                <!-- Modal -->
<div class="modal fade" id="id{{obj.pk}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">Do you want to remove the series?</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            Series <b>"{{ obj.book_series }}"</b> will be deleted.
            Please click delete button.<br>
            <br>
            <form action="{% url 'reference_book:series-delete' pk=obj.pk %}" method="post">
                {% csrf_token %}
                <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <input type="submit" value="Delete" class="btn btn-danger">
            </form>
        </div>
        </div>
      </div>
    </div>
  </div>
            </tbody>
        </div>
        {% endfor %}
        </table>
        {% endblock content %}