src/admin_portal/urls.py
from django.urls import path
from . import views


app_name = 'admin_portal'
urlpatterns = [
    path('', views.AdminPortalView.as_view(), name='admin_portal'),
]

src/carts/urls.py
from django.urls import path
from . import views

app_name = 'carts'
urlpatterns = [
    path('update_cart/', views.CartUpdate.as_view(), name='cart_update'),
    path('delete_good_in_cart/<int:pk>', views.DeleteGoodInCartView.as_view(), name='delete_good_in_cart'),
    path('', views.CartView.as_view(), name='cart_edit'),
]

src/catalog/urls.py
from django.urls import path
from . import views

app_name = "catalog"
urlpatterns = [
    path('', views.CatalogView.as_view(), name='catalog'),
    path('book/<int:pk>/', views.BookDetail.as_view(), name='book_detail'),
]

src/home_page/urls.py
from django.urls import path
from . import views 


app_name = "home_page"
urlpatterns = [
    path('', views.HomePage.as_view(), name='home_page'),
    path('login/', views.login_request, name='login'),
    path('register/', views.register_request, name='register'),
    path('logout/', views.logout_request, name= "logout"),
    
]

src/proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from catalog.views import SearchResultView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('refs/', include ('reference_book.urls', namespace = 'reference_book')),
    path('', include ('home_page.urls', namespace = 'home_page')),
    path('prod_card/', include('prod_card.urls', namespace='prod_card')),
    path('catalog/', include('catalog.urls', namespace="catalog")),
    path('search/', SearchResultView.as_view(), name='search_results'),
    path('carts/', include('carts.urls', namespace="carts")),
    path('order/', include('order.urls', namespace="order")),
    path('admin_portal/', include('admin_portal.urls', namespace="admin_portal")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/prod_card/models.py
from django.db import models
from reference_book.models import Author
from reference_book.models import Series
from reference_book.models import Genre
from reference_book.models  import Publishing
from django.urls import reverse_lazy
from django.utils.datetime_safe import date
from django.core.exceptions import ValidationError

# Create your models here.

class Books(models.Model):
    
    name = models.CharField(
       max_length=60,
       verbose_name="Book name")

    logo = models.ImageField(
        verbose_name="Book logotip",
        upload_to='uploads/%Y/%m/%d/',
        blank=True,
        null=True)

    author = models.ManyToManyField(
        Author)

    price = models.DecimalField(
        max_digits=6, 
        decimal_places=2,
        verbose_name="Price",
        help_text="Currency in BYN")

    series = models.ForeignKey(
        Series,
        verbose_name="Series",
        on_delete=models.PROTECT)

    genre = models.ManyToManyField(
        Genre)

    publishing_year=models.CharField(
        max_length=10,
        verbose_name="Publishing year")

    pages = models.IntegerField(
        verbose_name="Pages")

    binding = models.CharField(
        max_length=30,
        verbose_name="Binding")

    format = models.CharField(
        max_length=8,
        verbose_name="Format")

    isbn = models.CharField(
        max_length=25,
        verbose_name="ISBN")

    weight = models.IntegerField(
        verbose_name="Weight")

    age_restriction = models.IntegerField( 
        verbose_name="Age restriction")

    publishing = models.ForeignKey(
        Publishing,
        verbose_name="Publishing",
        on_delete=models.PROTECT)

    available_books = models.IntegerField(
        verbose_name="Quantity  of books available")

    activity = models.CharField(
        max_length = 3,
        verbose_name="In stock")

    rating = models.DecimalField(
        max_digits=2, 
        decimal_places=1,
        verbose_name="Rating")

    date_of_addition = models.DateField(
        verbose_name="Date of addition")

    modification_date = models.DateTimeField(
        auto_now=True,
        verbose_name="Date the card was last modified")

    description = models.TextField(
        blank = True,
        null = True )
    

    def get_absolute_url(self):
        return reverse_lazy('prod_card:prod_card_detail', kwargs={'pk': self.pk})

    def clean(self):
        if str(self.date_of_addition) > str(date.today()):
            raise ValidationError({'date_of_addition': 'Must not be later than today!'})
            
    def __str__(self):
        return str(self.name)
        
    

src/home_page/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, ReadOnlyPasswordHashField
from catalog.models import AppUser
from django.core.exceptions import ValidationError
from django.db import models

#Django Admin

class UserChangeForm(forms.ModelForm):
    password = ReadOnlyPasswordHashField()
    class Meta:
        model = AppUser
        fields = (
            "username",
            "email",
            "name",
            "surname",
            "phone",
            "country",
            "city",
            "index",
            "address",
            "reserve_address",
            "password",
            "additional_info"
        )


class MyUserCreationForm(forms.ModelForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = AppUser
        fields = (
            "username",
            "email",
            "name",
            "surname",
            "phone",
            "country",
            "city",
            "index",
            "address",
            "reserve_address",
            "password1",
            "password2",
            "additional_info"
            )

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise ValidationError("Passwords is not the same")
        return password2

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user

#Application

class UserForm(UserCreationForm):
    email = forms.EmailField(required=True)
    index = forms.IntegerField(required=True)
    name = forms.CharField(required=True, max_length=30)
    surname = forms.CharField(required=True, max_length=30)
    phone = forms.IntegerField(required=True, help_text="Enter the number.")
    country = forms.CharField(required=True)
    city = forms.CharField(required=True, max_length=30)
    address = forms.CharField(required=True, max_length=60)
    reserve_address = forms.CharField(required=False, max_length=60)
    additional_info = forms.CharField(required=False, max_length=150)



    class Meta:
        model = AppUser
        fields = (

            "username",
            "email",
            "name",
            "surname",
            "phone",
            "country",
            "city",
            "index",
            "address",
            "reserve_address",
            "password1",
            "password2",
            "additional_info",

            )

    def save(self, commit=True):
        user = super(UserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        user.name = self.cleaned_data['name']
        user.surname = self.cleaned_data['surname']
        user.country = self.cleaned_data['country']
        user.city = self.cleaned_data['city']
        user.index = self.cleaned_data['index']
        user.address = self.cleaned_data['address']
        user.reserve_address = self.cleaned_data['reserve_address']
        user.additional_info = self.cleaned_data['additional_info']



        if commit:
            user.save()

        return user

src/home_page/views.py
from django.shortcuts import render, redirect
from django.views import generic
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from .forms import UserForm
from django.contrib.auth.forms import AuthenticationForm
from reference_book.models import Author
from prod_card.models import Books
def login_request(request):

    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            print(username, password)
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"Logged in as {username}.")
                next_param = request.POST.get('next')
                if next_param:
                    url = next_param
                else:
                    url = '/'
                return HttpResponseRedirect(url)
                #return HttpResponseRedirect('/')
            else:
                messages.error(request,"The username or password you entered is incorrect.")
        else:
            messages.error(request,"The username or password you entered is incorrect.")
    form = AuthenticationForm()
    return render(request=request, template_name="home_page/login.html", context={"login_form":form})

#Create
def register_request(request):
    if request.method == "POST":
        form = UserForm(request.POST)

        if form.is_valid():
            user = form.save()
            login(request, user)
            next_param = request.POST.get('next')
            if next_param:
                url = next_param
            else:
                url = '/'
            return HttpResponseRedirect(url)
            #return HttpResponseRedirect('/')
        else:
            messages.error(request, "Registration failed.Enter correct data.")
    else:
            messages.error(request, "Registration failed.Enter correct data.")
    form = UserForm()
    return render (request=request, template_name="home_page/register.html", context={"register_form":form})


def logout_request(request):
	logout(request)
	messages.info(request, "Logged out.")
	return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

class HomePage(generic.TemplateView):
    template_name = 'home_page/home_page.html'

    def get_context_data(self, *args, **kwargs):

        context = super().get_context_data(*args, **kwargs)
        context['books'] = Books.objects.get(pk=3)
        context['books1'] = Books.objects.get(pk=2)
        context['books2'] = Books.objects.get(pk=1)

        return context

src/home_page/templates/home_page/home_page.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'bs/css/bootstrap.min.css' %}" rel="stylesheet">
    <script src="{% static 'bs/js/bootstrap.min.js' %}"></script>
    <link href="{% static 'bs/css/custom.css' %}" rel="stylesheet">
<body>


    <header>
      <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="/">BSHOP</a><br>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="/catalog">Catalog</a>
              </li>

              <li class="nav-item">
                <a class="nav-link active" href="/refs/rb/">Authors</a>
              </li>

              <li class="nav-item">
                <a class="nav-link active" href="/refs/rb-genre/">Genres</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" href="/refs/rb-Publishing/">Publishing</a>
              </li>

              {% if perms.prod_card.delete_books%}
              <li class="nav-item">
                <a class="nav-link active" href="{% url 'admin_portal:admin_portal' %}">Administration portal</a>
              </li>
              {% endif %}

              <li class="nav-item">
                <a class="nav-link active" href="{% url 'carts:cart_edit' %}">Order</a>
              </li>
            </ul>
              <ul class="navbar-nav">
                <li class="nav-item">
                  <a class="nav-link"  href="https://www.nbrb.by/statistics/rates/ratesdaily.asp">2.5 USD/BYN</a>
                </li>
              </ul>

              <form action="{% url 'search_results' %}" method="get" class="d-flex" role="search">
                <input name="q" type="text" class="form-control me-2" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-info me-4" type="submit">
                  <i class="bi bi-search">
                  </i>
                </button>
              </form>

            <li style="list-style-type: none">
            {% if user.is_authenticated %}
      <span class="navbar-text mr-2">{{ user }}</span>
      <a href="/logout" class="btn btn-outline-light"><i class="bi bi-box-arrow-right"></i></a>
    {% else %}
      <a href="{% url 'home_page:login' %}" class="btn btn-outline-light">Log in</a></a>
      <a href="{% url 'home_page:register' %}" class="btn btn-outline-light">Sign up</a>
    {% endif %}

            </li>
          </div>
        </div>
      </nav>
    </header>

  <main>
    <div id="myCarousel" class="carousel slide" data-bs-ride="carousel">
      <div class="carousel-indicators">
        <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
      </div>
      <div class="carousel-inner">
        <div class="carousel-item active">
            <image src="https://st.depositphotos.com/1003829/2984/i/450/depositphotos_29843121-stock-photo-opened-magic-book-with-magic.jpg" alt="image books" width="100%" height="80%" >
            <div class="container">
            <div class="carousel-caption text-start">
              <h1>Books for every taste only with us</h1>
            </div>
          </div>
        </div>
        <div class="carousel-item">
            <image src="https://static8.depositphotos.com/1170638/833/i/600/depositphotos_8335286-stock-photo-library-of-old-books.jpg" alt="image books" width="100%" height="80%">
          <div class="container">
            <div class="carousel-caption">
              <p><a class="btn btn-dark" href="catalog/">View catalog</a></p>
            </div>
          </div>
        </div>
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>


    <div class="container marketing">
      <div class="row">
        <div class="col-lg-4">
          <h2 class="fw-normal">Оскар Уайльд</h2>
          <p>Один из самых известных драматургов позднего Викторианского периода, одна из ключевых фигур эстетизма и европейского модернизма.</p>
          <p><a class="btn btn-dark" href="https://ru.wikipedia.org/wiki/%D0%A3%D0%B0%D0%B9%D0%BB%D1%8C%D0%B4,_%D0%9E%D1%81%D0%BA%D0%B0%D1%80">View details &raquo;</a></p>
        </div>
        <div class="col-lg-4">
          <h2 class="fw-normal">Эрих Мария Ремарк</h2>
          <p>Его роман «На Западном фронте без перемен» (1929) считается самым популярным антивоенным романом ХХ века.</p>
          <p><a class="btn btn-dark" href="https://ru.wikipedia.org/wiki/%D0%A0%D0%B5%D0%BC%D0%B0%D1%80%D0%BA,_%D0%AD%D1%80%D0%B8%D1%85_%D0%9C%D0%B0%D1%80%D0%B8%D1%8F#:~:text=Erich%20Maria%20Remarque%2C%20%D0%BF%D1%80%D0%B8%20%D1%80%D0%BE%D0%B6%D0%B4%D0%B5%D0%BD%D0%B8%D0%B8,%D0%BF%D0%BE%D0%BF%D1%83%D0%BB%D1%8F%D1%80%D0%BD%D1%8B%D0%BC%20%D0%B0%D0%BD%D1%82%D0%B8%D0%B2%D0%BE%D0%B5%D0%BD%D0%BD%D1%8B%D0%BC%20%D1%80%D0%BE%D0%BC%D0%B0%D0%BD%D0%BE%D0%BC%20%D0%A5%D0%A5%20%D0%B2%D0%B5%D0%BA%D0%B0.">View details &raquo;</a></p>
        </div>
        <div class="col-lg-4">
          <h2 class="fw-normal">Джордж Оруэлл</h2>
          <p>Его работы отличаются простым стилем изложения, критикой тоталитаризма и поддержкой демократического социализма.</p>
          <p><a class="btn btn-dark" href="https://ru.wikipedia.org/wiki/%D0%94%D0%B6%D0%BE%D1%80%D0%B4%D0%B6_%D0%9E%D1%80%D1%83%D1%8D%D0%BB%D0%BB#:~:text=%D0%95%D0%B3%D0%BE%20%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%8B%20%D0%BE%D1%82%D0%BB%D0%B8%D1%87%D0%B0%D1%8E%D1%82%D1%81%D1%8F%20%D0%BF%D1%80%D0%BE%D1%81%D1%82%D1%8B%D0%BC%20%D1%81%D1%82%D0%B8%D0%BB%D0%B5%D0%BC,%D1%82%D0%BE%D1%82%D0%B0%D0%BB%D0%B8%D1%82%D0%B0%D1%80%D0%B8%D0%B7%D0%BC%D0%B0%20%D0%B8%20%D0%BF%D0%BE%D0%B4%D0%B4%D0%B5%D1%80%D0%B6%D0%BA%D0%BE%D0%B9%20%D0%B4%D0%B5%D0%BC%D0%BE%D0%BA%D1%80%D0%B0%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B3%D0%BE%20%D1%81%D0%BE%D1%86%D0%B8%D0%B0%D0%BB%D0%B8%D0%B7%D0%BC%D0%B0.&text=%D0%A1%D0%B0%D0%BC%D1%8B%D0%B5%20%D0%B8%D0%B7%D0%B2%D0%B5%D1%81%D1%82%D0%BD%D1%8B%D0%B5%20%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%8B%20%D0%9E%D1%80%D1%83%D1%8D%D0%BB%D0%BB%D0%B0%20%D0%B2%D0%BA%D0%BB%D1%8E%D1%87%D0%B0%D1%8E%D1%82,%C2%AB1984%C2%BB%20(1948).">View details &raquo;</a></p>
        </div>


      <!-- cards -->

      <div class="card" style="width: 18rem;">
        <img src="{{ books.logo.url }}" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">Оскар Уайльд. "Саломея"</h5>
          <p class="card-text">В основе трагедии лежит история Саломеи, персонажа Нового Завета (имя в Библии не названо, впервые оно встречается у Иосифа Флавия).</p>
          <a href="{% url 'catalog:book_detail' pk=4 %}" class="btn btn-primary">Buy</a>
        </div>
      </div>


      <div class="card" style="width: 18rem;">
        <img src="{{ books1.logo.url }}" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">Эрих Мария Ремарк. "Три товарища"</h5>
          <p class="card-text">Действие происходит в Германии с марта 1928 по март 1929 года. Три товарища — Робби, Отто Кёстер и Готтфрид Ленц содержат небольшую авторемонтную мастерскую.</p>
          <a href="{% url 'catalog:book_detail' pk=2 %}" class="btn btn-primary">Buy</a>
        </div>
      </div>

      <div class="card" style="width: 18rem;">
  <img src="{{ books2.logo.url }}" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">Джордж Оруэлл. "1984"</h5>
    <p class="card-text">Роман «1984» считается одним из образцов антиутопии.</p>
    <a href="{% url 'catalog:book_detail' pk=1 %}" class="btn btn-primary">Buy</a>
  </div>
</div>


    <footer class="py-3 my-4">
        <div class="shadow p-3 mb-5 bg-body rounded">
        <div class="container">

          <p class="text-center text-muted">&copy; 2022 BSHOP, Inc</p>
        </div>
        </div>
    </footer>
  </main>
<script src={% static "bs/js/bootstrap.bundle.min.js" %}> </script>

</body>
</html>

src/home_page/templates/home_page/login.html
{% extends "base.html" %}

{% block content %} 

{% load crispy_forms_tags %}         


<div class="container py-5">
	<h1>Login</h1>
	<form method="POST">
        {% if messages %}
        <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
        </ul>
        {% endif %}
		{% csrf_token %}
		{{ login_form|crispy }}                    
		<button class="btn btn-primary" type="submit">Log in</button>
	</form>
	<p class="text-center">Are you still not registered? <a href="/register">Sign up</a> now.</p>
</div>

{% endblock %}

src/home_page/templates/home_page/register.html
{% extends "base.html" %}

{% block content %} 

{% load crispy_forms_tags %}         


<div class="container py-5">
	<h1>Register</h1>
	<form method="POST">
        {% if messages %}
        <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
        </ul>
        {% endif %}
		{% csrf_token %}
		{{ register_form|crispy }}                    
		<button class="btn btn-primary" type="submit">Register</button>
	</form>	
</div>

{% endblock %}